services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  auth-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=supersecreto123diegopetconnect456
    depends_on:
      - mongo
